version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.5
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=mariadb_ereko
      - MARIADB_PASSWORD=mariadb_ereko
      - MARIADB_USER=ereko
      - MARIADB_DATABASE=ereko
    volumes:
      - ereko-db-persist:/var/lib/mysql
  myapp:
    image: symfony5_youtube-dl #docker.io/bitnami/symfony:5.3
    ports:
      - '8000:8000'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - SYMFONY_DATABASE_PASSWORD=mariadb_ereko
      - SYMFONY_DATABASE_HOST=mariadb
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=ereko
      - SYMFONY_DATABASE_NAME=ereko
    volumes:
      - '.:/app'
    depends_on:
      - mariadb
# this is for the persistence of the BDD
volumes:
  ereko-db-persist:

